on:
  push:
    branches:
      - master
name: Build and Deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@master

      - name: Install and Build
        run: |
          git branch
          npm install
          #node node_modules/@angular/cli/bin/ng build --prod
          ls